### ISSUE TITLE
May I ask what I should do to build it into a binary file?

### ISSUE THREAD

**Issue by Little-Potato01** [codex15/codeban#2]
Hello! What should I do to build it into a binary file, and what are the requirements or dependencies to install?

**Comment by codex15** [comment]
1.Install Golang
sudo apt update
sudo apt install golang
2.Build 
go build brute.go -o brute
3. Run
4. ./brute 
If you want to run it without to build it:
Install Golang (1)
Then run it with: 
go run brute.go 
For more infomations or any more ideas, please let me know! 
Thanks, CoDeX!
